[package]
name = "hyperpolyglot"
version = "0.1.0"
authors = ["Connor Monks <monkslc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"
pcre2 = "0.2.3"
phf = "0.8"
regex = "1.3.5"

[build-dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
pcre2 = "0.2.3"
phf_codegen = "0.8.0"
serde = { version = "1.0.105", features = ["derive"] }
serde_yaml = "0.8"
